spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:mem:board;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: oauth
logging.level:
  org.hibernate.SQL: debug
  org.springframework.security.oauth2.client: DEBUG
  org.springframework.security.web.authentication: DEBUG
  org.springframework.web.client.RestTemplate: DEBUG

